version: '3.8'
services:
  api:
    container_name: lumen
    build:
      context: ../project
      dockerfile: ../deploy/docker/php/Dockerfile
    ports:
      - 9000:9000
    working_dir: /var/www
    command: php -S localhost:9000 -t public
    depends_on:
      - db
  db:
    container_name: pgsql
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "lumen"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"