version: '3'

services:
  php:
    build:
      context: ../project/
      dockerfile: ./docker/php/
    container_name: php
    user: '1000:1000'
    ports: ['8000:8000']
    command: 'php -S 0.0.0.0:8080 -t public'
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - ../project/:/var/www
  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_DB: "world"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
