version: "3.5"

services:
  lumen_post:
    ports:
      - "8000:8000"
    volumes:
      - ../project:/var/www/html
      - /var/www/html/vendor/
    build:
      context: ../project/
      dockerfile: ../deploy/docker/php/Dockerfile
    command: php -S localhost:8080 -t public
    restart: always
    depends_on:
      - lumen_post_db

  lumen_post_db:
    image: postgres:12.3-alpine
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lumen