version: '3'

services:
  php:
    build: './docker/php/'
    user: '1000:1000'
    volumes: [ './../project/:/app' ]
    working_dir: './../project/app'
    ports: ['8000:8000']
    command: 'php -S 0.0.0.0:8000 -t public'
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "world"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
