
  
version: '3.9'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ../
      dockerfile: deploy/docker/Dockerfile
    restart: unless-stopped
    tty: true
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: docker/nginx
    ports:
      - 80:80
    volumes:
      - ../project/:/var/www
    depends_on:
      - php-fpm
  
  db:
    image: postgres
    tty: true
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "lumen"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 63:8080
